---
- name: Create VM
  community.vmware.vmware_guest:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}' 
    validate_certs: no 
    datacenter: "{{vcenter_datacenter}}"
    cluster: '{{vcenter_cluster}}'    
    folder: /
    name: '{{ vm_name }}'
    state: present
    guest_id: ubuntu64Guest
    cdrom:
        - controller_number: 0
          unit_number: 0
          state: present
          type: iso
          iso_path: '[{{ iso_datastore }}] {{ install_iso }}'
    disk:
    - size_gb: '{{ vm_disk_gb | default(40) | string }}'
      type: thin
      datastore: '{{ vm_datastore }}'
    hardware:
      memory_mb: '{{ vm_memory_mb | default(2048) | string }}'
      num_cpus: '{{ vm_num_cpus | default(2) | string }}'
      nested_virt: '{{ nested_virtualization|default(true) }}'
      scsi: lsilogicsas
    networks:
    - name: "{{ vm_network | default('VM Network') }}"
      device_type: e1000
    wait_for_ip_address: no
  delegate_to: localhost
  register: deploy_vm

- name: Set boot order
  community.vmware.vmware_guest_boot_manager:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'   
    validate_certs: no  
    name: '{{ vm_name }}'
    boot_delay: 1000
    enter_bios_setup: False
    boot_retry_enabled: True
    boot_retry_delay: 20000
    boot_firmware: bios
    secure_boot_enabled: False
    boot_order:
      - disk
      - cdrom
      - ethernet
      - floppy
  delegate_to: localhost
  register: vm_boot_order

- name: Power-On the virtual machine
  community.vmware.vmware_guest_powerstate:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'    
    validate_certs: no 
    name: '{{ vm_name }}'
    state: powered-on
  delegate_to: localhost
  register: powerstate

- name: Wait for 30 seconds for boot
  wait_for: timeout=30
  delegate_to: localhost

- name: Select text based installer
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - DOWNARROW
     - ENTER
  delegate_to: localhost

- name: Wait for 45 seconds for text installer to load
  wait_for: timeout=45
  delegate_to: localhost

- name: press enter on license prompt
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: ENTER
  delegate_to: localhost

- name: press enter on target disk prompt
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: ENTER
  delegate_to: localhost

# - name: set location to Unitied States
#   community.vmware.vmware_guest_sendkey:
#     hostname: '{{ vcenter_address }}'
#     username: '{{ vcenter_username }}'
#     password: '{{ vcenter_password }}'     
#     validate_certs: no 
#     name: "{{ vm_name }}"
#     keys_send: 
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - ENTER
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - UPARROW
#      - ENTER
#      - DOWNARROW
#      - DOWNARROW
#      - DOWNARROW
#   delegate_to: localhost

- name: set timezone to America/Los_Angeles
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - UPARROW
     - UPARROW
     - ENTER
     - DOWNARROW
     - DOWNARROW
     - DOWNARROW
     - DOWNARROW
     - DOWNARROW
     - DOWNARROW
     - DOWNARROW
     - DOWNARROW
     - DOWNARROW
     - DOWNARROW
     - DOWNARROW
     - DOWNARROW
     - DOWNARROW
     - DOWNARROW
     - DOWNARROW
     - DOWNARROW
     - DOWNARROW
     - ENTER
     - DOWNARROW
     - DOWNARROW
  delegate_to: localhost

# - name: set keyboard to U.S.English
#   community.vmware.vmware_guest_sendkey:
#     hostname: '{{ vcenter_address }}'
#     username: '{{ vcenter_username }}'
#     password: '{{ vcenter_password }}'     
#     validate_certs: no 
#     name: "{{ vm_name }}"
#     keys_send: 
#      - UPARROW
#      - ENTER
#      - DOWNARROW
#      - DOWNARROW
#      - DOWNARROW
#      - DOWNARROW
#      - DOWNARROW
#      - DOWNARROW
#      - DOWNARROW
#      - DOWNARROW
#      - DOWNARROW
#      - DOWNARROW
#      - DOWNARROW
#      - DOWNARROW
#      - DOWNARROW
#      - DOWNARROW
#      - DOWNARROW
#      - DOWNARROW
#      - ENTER
#   delegate_to: localhost

- name: Wait for 30 seconds
  wait_for: timeout=30
  delegate_to: localhost

- name: Accept configuration
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - DOWNARROW
     - ENTER
  delegate_to: localhost


- name: set password
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    string_send: "{{ vm_password }}"
  delegate_to: localhost

- name: confirm password
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: DOWNARROW
    string_send: "{{ vm_password }}"
  delegate_to: localhost

- name: set email
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - DOWNARROW
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
    string_send: "mail@example.com"
  delegate_to: localhost

- name: Wait for 30 seconds
  wait_for: timeout=30
  delegate_to: localhost

- name: Accept configuration
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - DOWNARROW
     - ENTER
  delegate_to: localhost

- name: set hostname
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - UPARROW
     - UPARROW
     - UPARROW
     - UPARROW
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
    string_send: "{{vm_hostname}}.{{vm_domain}}"
  delegate_to: localhost

- name: set IP
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - DOWNARROW
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
    string_send: "{{vm_address}}"
  delegate_to: localhost

- name: set CIDR
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - RIGHTARROW
     - RIGHTARROW
     - RIGHTARROW
     - RIGHTARROW
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
    string_send: "{{vm_netmask_cidr}}"
  delegate_to: localhost

- name: set gateway
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - DOWNARROW
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
    string_send: "{{vm_gateway}}"
  delegate_to: localhost

- name: set dns
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - DOWNARROW
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
     - BACKSPACE
    string_send: "{{vm_dns_server}}"
  delegate_to: localhost

- name: Wait for 30 seconds
  wait_for: timeout=30
  delegate_to: localhost

- name: Accept configuration
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - DOWNARROW
     - ENTER
  delegate_to: localhost

- name: Begin Installation
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: 
     - RIGHTARROW
     - ENTER
  delegate_to: localhost

- name: Wait for 10 minutes for install
  wait_for: timeout=600
  delegate_to: localhost

# login
- name: login
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    string_send: "root"
  delegate_to: localhost

- name: press enter
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: "ENTER"
  delegate_to: localhost

- name: password
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    string_send: "{{vm_password}}"
  delegate_to: localhost

- name: press enter
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: "ENTER"
  delegate_to: localhost

- name: apt update
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    string_send: "apt update"
  delegate_to: localhost

- name: press enter
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: "ENTER"
  delegate_to: localhost

- name: Wait for 60 seconds
  wait_for: timeout=60
  delegate_to: localhost

- name: apt update
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    string_send: "apt install open-vm-tools -y"
  delegate_to: localhost

- name: press enter
  community.vmware.vmware_guest_sendkey:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'     
    validate_certs: no 
    name: "{{ vm_name }}"
    keys_send: "ENTER"
  delegate_to: localhost

- name: Wait for VMware tools to become available 
  community.vmware.vmware_guest_tools_wait:
    hostname: '{{ vcenter_address }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'   
    validate_certs: no 
    name: '{{ vm_name }}'
  delegate_to: localhost
  retries: 10
  delay: 60
  register: result           
  until: result is succeeded
